name: fusionbible
favicon: null
layout_spectrum: 0.9134
typography_spectrum: 0.19756
title: Fusion Bible
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b9c1c0'
    - '#455a57'
    - '#ff844d'
    - '#978280'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
